#!/bin/bash

set -xe

export PATH=$PATH:$HOME/bin

mkdir -p ~/src ~/bin ~/opt ~/tmp

mkdir -p ~/src/github.com/lambdasawa
rm -f ~/src/github.com/lambdasawa/dotfiles
ln -sf $HOME/.dotfiles $HOME/src/github.com/lambdasawa/
mv $HOME/src/github.com/lambdasawa/.dotfiles $HOME/src/github.com/lambdasawa/dotfiles

for path in $(find ./bin -type f | grep -v '.sh$'); do
  mkdir -p $HOME/$(dirname $path)
  ln -sf $PWD/$path $HOME/$path
done

for path in $(find . -type f | grep -v '.git/' | grep -e '^\./\.'); do
  mkdir -p $HOME/$(dirname $path)
  ln -sf $PWD/$path $HOME/$path
done

if is-mac; then
  if ! command -v brew; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  brew upgrade

  if ! command -v fish; then
    brew install fish
  fi
elif is-debian; then
  sudo apt update -y
  sudo apt upgrade -y

  if ! command -v fish; then
    sudo apt install -y fish
  fi
fi

echo "./apply success!"
