#!/bin/bash

set -xe

mkdir -p ~/src ~/bin ~/opt ~/tmp

if ! command -v brew; then
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

if ! command -v fish; then
  brew install fish
fi

for path in $(find . -type f | grep -v '.git/' | grep -e '^\./\.'); do
  mkdir -p $HOME/$(dirname $path)
  ln -sf $PWD/$path $HOME/$path
done
