# mise install
[tools]
terraform = "1.10.2"
dotnet = "9.0.101"
rust = "1.83.0"
dart = "3.6.0"
flutter = "3.27.0-stable"
python = "3.13.1"
ruby = "3.3.6"
node = "23.4.0"
go = "1.23.4"
gradle = "8.11.1"
java = "23.0.1"

[settings]
experimental = true

## cp .env.example .env
## touch .envrc.sh
## mkdir bin/
## mise trust
# [env]
# HOGE = 'fuga'
# GIT_SHA = "{{exec(command='git rev-parse HEAD')}}"
# _.file = '.env'
# _.source = ".envrc.sh"
# _.path = ["./bin"]
# _.python.venv = { path = ".venv", create = true }

## mise run
# [tasks.default]
# run = """
# echo "Hello, mise tasks.default!"
# """

## mise run exec
## mise watch -t exec
# [tasks.exec]
# sources = ['**/*.py']
# run = "python main.py"
