[tools]
terraform = "1.10.5"
dotnet = "9.0.102"
rust = "1.84.1"
dart = "3.6.2"
flutter = "3.27.3-stable"
python = "3.13.1"
ruby = "3.4.1"
node = "23.7.0"
go = "1.23.5"
gradle = "8.12"
java = "23.0.2"

[settings]
experimental = true
