[tools]
terraform = "1.10.3"
dotnet = "9.0.101"
rust = "1.83.0"
dart = "3.6.0"
flutter = "3.27.1-stable"
python = "3.13.1"
ruby = "3.3.6"
node = "23.5.0"
go = "1.23.4"
gradle = "8.12"
java = "23.0.1"

[settings]
experimental = true
