[tools]
terraform = "1.11.4"
dotnet = "9.0.203"
rust = "1.86.0"
dart = "3.7.2"
flutter = "3.29.2-stable"
python = "3.13.3"
ruby = "3.4.2"
node = "23.11.0"
go = "1.24.2"
gradle = "8.13"
java = "24.0.0"
deno = "2.2.9"
bun = "1.2.9"
zig = "0.14.0"

[settings]
experimental = true
