[tools]
terraform = "1.11.2"
dotnet = "9.0.202"
rust = "1.85.1"
dart = "3.7.2"
flutter = "3.29.2-stable"
python = "3.13.2"
ruby = "3.4.2"
node = "23.10.0"
go = "1.24.1"
gradle = "8.13"
java = "24.0.0"
deno = "2.2.4"
bun = "1.2.5"
zig = "0.14.0"

[settings]
experimental = true
