[tools]
terraform = "1.11.4"
dotnet = "9.0.203"
rust = "1.86.0"
dart = "3.7.3"
flutter = "3.29.3-stable"
python = "3.13.3"
ruby = "3.4.3"
node = "23.11.0"
go = "1.24.2"
gradle = "8.14"
java = "24.0.1"
deno = "2.3.1"
bun = "1.2.10"
zig = "0.14.0"

[settings]
experimental = true
