# mise install
[tools]
terraform = "1.9.5"
dotnet = "8.0.401"
rust = "1.81.0"
dart = "3.5.3"
flutter = "3.24.3-stable"
python = "3.12.6"
ruby = "3.3.5"
node = "22.8.0"
go = "1.23.1"
gradle = "8.10.1"
java = "24.0.0-loom+7-60"

[settings]
experimental = true

## cp .env.example .env
## touch .envrc.sh
## mkdir bin/
## mise trust
# [env]
# HOGE = 'fuga'
# GIT_SHA = "{{exec(command='git rev-parse HEAD')}}"
# _.file = '.env'
# _.source = ".envrc.sh"
# _.path = ["./bin"]
# _.python.venv = { path = ".venv", create = true }

## mise run
# [tasks.default]
# run = """
# echo "Hello, mise tasks.default!"
# """

## mise run exec
## mise watch -t exec
# [tasks.exec]
# sources = ['**/*.py']
# run = "python main.py"
